name: Build notification-hub-models package

on:
  workflow_dispatch:
    inputs:
      RELEASE_TAG:
        description: 'The release tag'
        required: true
        default: 'v1.0.0'

jobs:
  build-notification-hub-models-package:
    uses: 7egend/workflows/.github/workflows/release-npm-package.yml@main
    secrets: inherit
    permissions:
        packages: write
        contents: read
    with:
      project-path: ./packages/nodejs/models
      SLACK_CHANNEL: hub
      AUTHOR_NAME: Tiago Barros
      PROJECT_NAME: Workflows
      RELEASE_TAG: ${{ inputs.RELEASE_TAG }}
      RELEASE_CHANGELOG: Hardcoded value
      LINKS_SOURCE_CODE: https://gitlab.com/7egend/projects/home/other/tests/apagame
      LINKS_REGISTRY: https://gitlab.com/7egend/projects/home/other/tests/apagame/registry
