name: Build notification-hub-models package

on:
  workflow_dispatch:
    inputs:
      slack-channel:
        description: Slack channel to post a notification
        required: true
        default: hub
      release-tag:
        description: Release tag
        required: true
        default: v1.0.0
      release-changelog:
        description: Version changelog
        required: true
        default: No release changelog provided

jobs:
  release-notification-hub-models-package:
    uses: 7egend/workflows/.github/workflows/release-npm-package.yml@main
    secrets: inherit
    permissions:
        packages: write
        contents: read
    with:
      package-path: ./packages/nodejs/models
      slack-channel: ${{ inputs.slack-channel }}
      author-name: Tiago Barros
      project-name: ${{ github.event.repository.name }}
      release-tag: ${{ inputs.release-tag }}
      release-changelog: ${{ inputs.release-changelog }}
      links-source-code: https://gitlab.com/7egend/projects/home/other/tests/apagame
      links-registry: https://gitlab.com/7egend/projects/home/other/tests/apagame/registry
