name: Build and deploy server/runner docker image

on:
  workflow_dispatch:
  push:
    branches:    
      - main
    tags:
      - '*.*.*'
    paths:
      - 'server/runner/**'

jobs:
  build-image:
    uses: 7egend/workflows/.github/workflows/build.yml@main
    permissions: write-all
    secrets: inherit
    with:
      DOCKERFILE_PATH: server/runner/Dockerfile
      CONTEXT_PATH: server/runner

  deploy-production-notification-hub-runner:
    uses: 7egend/workflows/.github/workflows/deploy.yml@main
    with:
      DEPLOYER_IMAGE: ghcr.io/${{ github.repository }}/devops/ansible:latest
      PLAYBOOK: playbooks/production/notification-hub/deploy.yaml
      KNOWN_HOSTS_FILE: ${{ vars.KNOWN_HOSTS_FILE }}
      ENVIRONMENT: production
    secrets:
      CI_BOT_SSH_PRIVATE_KEY: ${{ secrets.CI_BOT_SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
    needs: build-image
