name: Release notification-hub-models package

on:
  workflow_dispatch:
    inputs:
      slack-channel:
        description: Slack channel to post a notification
        required: true
        default: hub
      release-tag:
        description: Release tag
        required: true
      release-changelog:
        description: Version changelog
        required: true

jobs:  
  release-notification-hub-models-package:
    uses: 7egend/workflows/.github/workflows/release-npm-package.yml@main
    secrets: inherit
    permissions:
        packages: write
        contents: read
    with:
      package-path: ./packages/nodejs/models
      slack-channel: ${{ inputs.slack-channel }}
      author-name: ${{ github.triggering_actor }}
      project-name: ${{ github.event.repository.name }}
      release-tag: ${{ inputs.release-tag }}
      release-changelog: ${{ inputs.release-changelog }}
